# Generated by Django 4.1.7 on 2023-02-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compani',
            new_name='companisql',
        ),
        migrations.AlterModelOptions(
            name='companisql',
            options={'verbose_name': 'Компанія', 'verbose_name_plural': 'Компанії'},
        ),
    ]
