# Generated by Django 4.1.7 on 2023-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl', '0002_rename_compani_companisql_alter_companisql_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='compani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('industry', models.CharField(max_length=255, verbose_name='Галузь')),
            ],
        ),
        migrations.DeleteModel(
            name='companisql',
        ),
    ]
