# Generated by Django 4.1.7 on 2023-02-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kl', '0003_compani_delete_companisql'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compani',
            new_name='listofcompanies',
        ),
        migrations.AlterModelOptions(
            name='listofcompanies',
            options={'verbose_name': 'Компанія', 'verbose_name_plural': 'Компанії'},
        ),
    ]
